# Generated by Django 5.0.3 on 2024-04-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt_650', '0003_remove_student_cpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dt',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
